apiVersion: v1
kind: Service
metadata:
  name: invoice-service
  namespace: {{ include "invoice.namespace" . }}
  labels:
    {{- include "invoice.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: invoice-service
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
