# Invoice-Service (prod)
namespace: invoice-service

imagePullSecrets:
  - name: ghcr-secret

service:
  image: ghcr.io/emmguardia/invoice-service@sha256:22a03fd76d441be6252e55e674a32d3ef1ce3594e4d0cbbbea75a240a1e4d751
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 8080
  env:
    PORT: "8080"
    NODE_ENV: production
    TEMPLATES_DIR: /app/templates
    JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private_key.pem
    JWT_PUBLIC_KEY_PATH: /app/secrets/jwt_public_key.pem
    EMAIL_SERVICE_URL: http://email-service.email-service.svc.cluster.local:8080
  secretName: invoice-service-secrets
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
