# Invoice-Service (prod)
namespace: invoice-service

imagePullSecrets:
  - name: ghcr-secret

service:
  image: ghcr.io/emmguardia/invoice-service@sha256:6455d9ffdd8e1efe0f4cd9f631752f752d85dd271e38ee138c1f3d322715e0a8
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 8080
  env:
    PORT: "8080"
    NODE_ENV: production
    TEMPLATES_DIR: /app/templates
    JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private_key.pem
    JWT_PUBLIC_KEY_PATH: /app/secrets/jwt_public_key.pem
    EMAIL_SERVICE_URL: http://email-service.email-service.svc.cluster.local:8080
  secretName: invoice-service-secrets
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
